USE [master]
GO
CREATE DATABASE $(DBName)
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'$(DBName)', FILENAME = N'$(DataPath)\$(DBName).mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ),
 FILEGROUP [CEBLOB] 
( NAME = N'$(DBName)_CEBLOB01', FILENAME = N'$(BlobPath)/$(DBName)_CEBLOB01.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ) ,
 FILEGROUP [CEDATA]  DEFAULT 
( NAME = N'$(DBName)_CEData01', FILENAME = N'$(DataPath)/$(DBName)_CEData01.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [CEINDEX] 
( NAME = N'$(DBName)_CEINDEX01', FILENAME = N'$(IndexPath)/$(DBName)_CEINDEX01.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'$(DBName)_log', FILENAME = N'$(LogPath)/$(DBName)_log.ldf' , SIZE = 11264KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE $(DBName) SET READ_COMMITTED_SNAPSHOT ON
GO