apiVersion: v1
kind: Service
metadata:
  name: cpeserver-cluster
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: cpeserver-cluster
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cpeserver-cluster
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cpeserver-cluster
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                  - cpeserver-cluster
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: <REGISTRY>/cpe:latest
        imagePullPolicy: Always
        name: cpeserver-cluster
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https
        readinessProbe:
          httpGet:
            path: /cpe
            port: 9080
            httpHeaders:
              - name: Content-Encoding
                value: gzip
          initialDelaySeconds: 10
          periodSeconds: 2
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides"
            subPath: cpe/configDropins/overrides
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/asa"
            subPath: cpe/asa
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/textext"
            subPath: cpe/textext
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/logs"
            subPath: cpe/logs
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/FileNet"
            subPath: cpe/FileNet
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/icmrules"
            subPath: cpe/icmrules
          - name: ecmcfgstore-pvc
            mountPath: "/opt/ibm/wlp/usr/servers/defaultServer/lib/bootstrap"
            subPath: cpe/bootstrap
      volumes:
        - name: ecmcfgstore-pvc
          persistentVolumeClaim:
            claimName: ecmcfgstore
